# Site settings
title: Average Talk by Average Developer
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Another Software Engineering blog. Sharing my experiences in this field in order to help others. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hakanozbay.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  hakanozbay

# Build settings
#markdown: kramdown
